language: node_js
node_js:
- "8"
before_install: 
before_deploy: 
deploy:
  provider: heroku
  email: rtaimal@gmail.com
  skip_cleanup: true
  api_key:
    secure: ErhspconTheHMZLjiqsYtpXiT31wkdX9TMrob8GPTdqdV1b8PrFHdH51/vNcSld/o624PQMJ7FZtCulQferR2t7yZ5c5qaYPCClqyb02BlmbJjwpidMmEMPZZIFwTX6OkuCsMkw3RrSTuj+05uOxcRjnIBoRdGNuPN3vOD0RVStynSCMW4Dk9Nk76rskXT5s7f0ae1Y02HbdCuNn/e5b2RCGRDpfyZq50FYD2hwptHb9gKdzB8fxFQCUTlDGs30tlTEiFgkPKTcQG9ZdCKuNhdx/dnYgi3GvmnOLZDGjXbQ2B+fhlIrNbYncxJzQ22b5bjlPmNShj4617J3G7oEpAzQk4dHhB9o/jRn3JWP8jrk8IA0wswL0ibfc5S4hPVcaeIVmKXcdocy/Ggx0zn+bJy9Z78zUO+X/0T2WtIndukRTQtqFt4BHsGo/WTEOForXBVmMqYKl/EUZnWYubbwpllVw3EIvu9k88lqWpOgVO/xBtdnUAPQngmjL/tJxUanVx5QdLEYtfaqLtLYE1+sKRkNDPZ68KJrWuiPi/X9l1QnJhNxOxuXbtqKRDD4AqWtfnVRcwY5VOaknrIL0q2QY1jazZTqBtBXeXjwIheLFOnCHx1Ij4hOmPHGNLzZtMOGyCbyXjiR2weFfKrcRZ+EMfsKcOfR64tvI/BbRLi8lwtk=
  app:
    master: miso-4208-TSDC
  on:
    repo: ir-taimal10/miso-4208-TSDC
env:
  global:
    secure: ErhspconTheHMZLjiqsYtpXiT31wkdX9TMrob8GPTdqdV1b8PrFHdH51/vNcSld/o624PQMJ7FZtCulQferR2t7yZ5c5qaYPCClqyb02BlmbJjwpidMmEMPZZIFwTX6OkuCsMkw3RrSTuj+05uOxcRjnIBoRdGNuPN3vOD0RVStynSCMW4Dk9Nk76rskXT5s7f0ae1Y02HbdCuNn/e5b2RCGRDpfyZq50FYD2hwptHb9gKdzB8fxFQCUTlDGs30tlTEiFgkPKTcQG9ZdCKuNhdx/dnYgi3GvmnOLZDGjXbQ2B+fhlIrNbYncxJzQ22b5bjlPmNShj4617J3G7oEpAzQk4dHhB9o/jRn3JWP8jrk8IA0wswL0ibfc5S4hPVcaeIVmKXcdocy/Ggx0zn+bJy9Z78zUO+X/0T2WtIndukRTQtqFt4BHsGo/WTEOForXBVmMqYKl/EUZnWYubbwpllVw3EIvu9k88lqWpOgVO/xBtdnUAPQngmjL/tJxUanVx5QdLEYtfaqLtLYE1+sKRkNDPZ68KJrWuiPi/X9l1QnJhNxOxuXbtqKRDD4AqWtfnVRcwY5VOaknrIL0q2QY1jazZTqBtBXeXjwIheLFOnCHx1Ij4hOmPHGNLzZtMOGyCbyXjiR2weFfKrcRZ+EMfsKcOfR64tvI/BbRLi8lwtk=
